/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      link: {type: 'doc', id: 'introduction'},
      items: [
        {type: 'autogenerated', dirName: 'introduction'},
      ],
    },
    {
      type: 'category',
      label: 'Config',
      link: {type: 'doc', id: 'config'},
      items: [
        {type: 'autogenerated', dirName: 'config'},
      ],
    },
    {
      type: 'category',
      label: 'API',
      link: {type: 'doc', id: 'api'},
      items: [
        {type: 'autogenerated', dirName: 'api'},
      ],
    },
    'contributing',
  ],
  referenceSidebar: [
    'reference/index',
    'reference/modules/annotations',
    'reference/modules/environment_node',
    'reference/classes/index.JestAllure2Reporter',
  ],
};

module.exports = sidebars;
